### PR TITLE
IntelliJ suggested performance fixes.

### PR DESCRIPTION
**Pull request by SM9CC**
Sorry about the wait, had to turn a bunch of IntelliJ features off to prevent it reformating code and changing things unrelated to the performance fixes.

### CODE REVIEW

**Comment by SM91337** [comment]
https://i.imgur.com/2rhefwF.png
https://i.imgur.com/epIj1nI.png
https://i.imgur.com/hpio4L3.png
https://i.imgur.com/VFYNywC.png
https://i.imgur.com/fZIpCQi.png
https://i.imgur.com/Npz1U0p.png
https://i.imgur.com/xSdsxvw.png
https://i.imgur.com/pHZfRYF.png
https://i.imgur.com/0j65lga.png
https://i.imgur.com/QQOcpCG.png
https://i.imgur.com/J5uKgYM.png
https://i.imgur.com/qI2Qw7N.png
https://i.imgur.com/2yHmgCf.png
https://i.imgur.com/JLiGEDy.png
https://i.imgur.com/k8NRnPR.png
https://i.imgur.com/llik1T4.png
https://i.imgur.com/wLgRqgL.png
https://i.imgur.com/3yILOfy.png
https://i.imgur.com/I6TD6UF.png

**Comment by SM91337** [comment]
Correct, they won't really affect performance during game play but either way does not hurt and no worries I try to help as much as I can with my limited Java knowledge.

**Comment by PT400C** [comment]
@SM9CC I just noticed that this PR points to our master branch. I will close it later and implement your changes with a new PR - credit for you will ofc be given.

**Comment by SM9CC** [comment]
All good

**Comment by SM9CC** [comment]
woops hit close and comment LUL

**Comment by PT400C** [comment]
This PR is now moved here #576

**Pull request closed without merging**
