### PR TITLE
Used IntelliJ reformat & Inspect to fix some perfornance issues & cle…

### PR DESCRIPTION
**Pull request by SM9CC**
IntelliJ has some lovely features which automate such a painstaking task.

### CODE REVIEW

**Comment by PT400C** [comment]
@SM9 Could you Quote certain p

**Comment by PT400C** [comment]
@SM9 Woops .. um, could you quote certain passages which fix performance issues?

**Comment by SM91337** [comment]
Yep, give me a few.

**Comment by SM91337** [comment]
https://github.com/JurassiCraftTeam/JurassiCraft2/pull/572

**Comment by PT400C** [comment]
I think this is actually useful but just too much stuff which changes just for reformatting purposes. Closing this so far.

**Pull request closed without merging**
