### PR TITLE
Naturally generated JC leaves now'll decay again

### LINKED ISSUE #384: Leaves not decaying on JC Trees
Seems that leaves from JC mod trees are not decaying when too far from nearby log blocks.

### PR DESCRIPTION
**Pull request by CraftedMods**
Closes #384. Also, this PR fixes that JC leaves that were placed by the player indeed did decay.

### CODE REVIEW

**Comment by CraftedMods** [comment]
Wait, don't merge it. I accidentally formatted the source file.

**Comment by CraftedMods** [comment]
Okay, now the new checks were pushed. I accidentally ammended the last commit to the last one in the branch, and had to reset by branch to fix it. Because of that this PR didn't contain any changes anymore and auto-closed. Sorry for these inconveniences.

**Comment by Cazsius** [comment]
@PT400C I know you wanted to test some things, if you could reply here to let us know once you've approved this, that would be appreciated.

Also @CraftedMods you've got a bit of conflicts from the merge of some other PRs

**Comment by PT400C** [comment]
@Cazsius @CraftedMods Probably I am blinded but I don't see any changes to the code, which means that there is no check for the wood types:
[Picture](https://image.ibb.co/fQ77oK/2018_08_17_07_40_18.png)

**Comment by CraftedMods** [comment]
I did squash the change into the last commit, you can see it here: https://github.com/JurassiCraftTeam/JurassiCraft2/pull/397/commits/54fd84d8236d2430c7432f38b1d5bd70e840adeb#diff-91ccee8f8f02a8b91027ccc7f6b5f071R97

**Comment by CraftedMods** [comment]
I adjusted the algorithm a bit, to make it more realistic: Now only logs with the same tree type as the leaves will prevent the leaves from decaying.

**Pull request merged**
