### PR TITLE
Check for null to avoid nullReferenceErrors

### PR DESCRIPTION
**Pull request by Shovinus**

### CODE REVIEW

**Comment by PT400C** [comment]
How is a case possible that the grinder has an input stack which isn't grindable?

**Comment by Shovinus** [comment]
Yeh, checking what should be inserted would be nice, so would checking for pull out and push in, i.e. enderio pulls out everything, not just the ground down items or empty buckets, meaning you have to make filters to automate it.

**Comment by Cazsius** [comment]
@Shovinus If you'd like to talk more about JurassiCraft or contribute more, feel free to add me on discord at Cazsius#2026

**Comment by PT400C** [comment]
I close that PR, as there is no further visible development on that. I'll rework the system how interacting with JC slots works in the future.

**Pull request closed without merging**
